name: Dev PR

on: push

permissions:
  contents: read
  pull-requests: read

jobs:
  check-pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install commitlint
        run: |
          npm install @commitlint/cli @commitlint/config-conventional
      - name: Check PR title follows conventional commits spec
        run: |
          echo "${{ github.event.pull_request.title }}" | npx commitlint --config '{"extends":["@commitlint/config-conventional"]}'
